[package]
name = "frontend"
version = "0.1.0"
authors = ["sved"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
mytodo = { path = ".." }
seed = "0.8.0"
wasm-bindgen = "0.2.68"
web-sys = "0.3.45"
